service:
- docker

script:
- docker build . -t packyzbq/prometheus/busybox-linux-mips64le:latest -f uclibc/Dockerfile
- docker login -u packyzbq -p $DOCKER_PASSWD
- docker push packyzbq/prometheus/busybox-linux-mips64le:latest
