service:
- docker

script:
- make build
- docker tag packyzbq/prometheus/busybox-linux-mips64le:latest  packyzbq/prom-busybox-linux-mips64le:latest
- docker login -u packyzbq -p $DOCKER_PASSWD
- docker push packyzbq/prom-busybox-linux-mips64le:latest
